name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build image
        run: docker build -t catty-reminders-app .

      - name: Run server
        run: |
          docker run -d --name app -p 8181:8181 catty-reminders-app
          sleep 5  # дать серверу время на запуск

      - name: Run tests
        run: |
          docker run --rm --network host catty-reminders-app python -m pytest