name: Deploy

on:
  push:
    tags: ["*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2433 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - uses: actions/checkout@v4
      - name: Deploy from GHCR
        run: |
          scp -P 2433 docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/user/
          ssh -t -p 2433 ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd /home/user
            docker-compose -f docker-compose.yml -p catty-reminders down || true
            docker-compose -f docker-compose.yml -p catty-reminders up -d
          EOF
