name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2433 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -p 2433 ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            echo "🚀 Начинаем развертывание демо-сайта..."
            mkdir -p /home/user/catty-reminders-app
            echo "📁 Копируем файлы сайта..."
            cp -r ./* /home/user/catty-reminders-app/
            source /home/user/catty-reminders-app/venv/bin/activate
            pip install -r /home/user/catty-reminders-app/requirements.txt
            systemctl restart catty-reminders-app.service
          EOF
